modLoader="javafml"
loaderVersion="[36,)"
license="MIT License"
issueTrackerURL="https://github.com/Mrthomas20121/ForegoingTweaker/issues"

[[mods]]
modId="foregoing_tweaker"
version="1.16.5-1.1.4"
displayName="Foregoing Tweaker"
displayURL="https://www.curseforge.com/minecraft/mc-mods/foregoing_tweaker"
#logoFile="tinkers_reforged_logo.png"
authors="Mrthomas20121"
description='''
Add Crafttweaker support to Industrial Foregoing
'''

[[dependencies.foregoing_tweaker]]
    modId="industrialforegoing"
    mandatory=true
    versionRange="[3.2,]"
    ordering="NONE"
    side="BOTH"
[[dependencies.foregoing_tweaker]]
	modId = "crafttweaker"
	mandatory = true
	versionRange = "[7.1,)"
	ordering = "NONE"
	side = "BOTH"