modLoader="javafml"
loaderVersion="[36,)"
license="MIT License"
issueTrackerURL="https://github.com/Mrthomas20121/ForegoingTweaker/issues"

[[mods]]
modId="foregoing_tweaker"
version="1.19.2-1.1.5"
displayName="Foregoing Tweaker"
displayURL="https://www.curseforge.com/minecraft/mc-mods/foregoing_tweaker"
#logoFile="tinkers_reforged_logo.png"
authors="Mrthomas20121"
description='''
Add Crafttweaker support to Industrial Foregoing
'''

[[dependencies.foregoing_tweaker]]
	modId = "crafttweaker"
	mandatory = true
	versionRange = "[9.1,)"
	ordering = "NONE"
	side = "BOTH"